Amigo Compatibility
selfcustody/MaixPy pull request #2
Opened 2022-04-05 18:50 UTC by odudex

Fixed json typos, removed py_lcd fill_rectangle check, changed full filled character to position 161

2022-04-18 04:07 UTC, jreesun requested changes
Looking good! Just have that one request about the config structure

2022-04-20 00:03 UTC, jreesun commented on projects/maixpy_twatch/builtin_py/board.py
> +    "sensor":{
`sensor` is here twice now

2022-04-20 19:11 UTC, jreesun approved these changes
LGTM! Thanks for making those changes.

After I merge this, can you update the MaixPy submodule in your krux branch/PR?

2022-04-20 19:12 UTC, merged

2022-04-20 20:33 UTC, odudex commented
MaixPy updated on my krux fork and PR.